from .models import Order, Product
from .database import SessionLocal, engine, Base


def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    if db.query(Order).first():
        db.close()
        return

    orders = [
        # --- Teslim edildi ---
        Order(order_id="101", customer_name="Ayşe Kaya", product_name="Organik Domates Kurusu",
              quantity=2, order_status="teslim_edildi", cargo_company="Yurtiçi Kargo",
              tracking_number="YK123456789", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-08", delay_risk=False, created_at="2026-05-05"),
        Order(order_id="102", customer_name="Mehmet Demir", product_name="Zeytinyağı",
              quantity=1, order_status="teslim_edildi", cargo_company="MNG Kargo",
              tracking_number="MNG987654321", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-09", delay_risk=False, created_at="2026-05-06"),
        Order(order_id="103", customer_name="Fatma Yıldız", product_name="El Yapımı Reçel",
              quantity=3, order_status="teslim_edildi", cargo_company="PTT Kargo",
              tracking_number="PTT445566778", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-07", delay_risk=False, created_at="2026-05-04"),
        Order(order_id="104", customer_name="Emre Çetin", product_name="Tarhana",
              quantity=2, order_status="teslim_edildi", cargo_company="Aras Kargo",
              tracking_number="AR112233445", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-06", delay_risk=False, created_at="2026-05-03"),
        Order(order_id="105", customer_name="Selin Koç", product_name="Kahve Çekirdeği",
              quantity=1, order_status="teslim_edildi", cargo_company="Yurtiçi Kargo",
              tracking_number="YK556677889", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-08", delay_risk=False, created_at="2026-05-05"),
        Order(order_id="106", customer_name="Bora Aydın", product_name="Doğal Sabun",
              quantity=4, order_status="teslim_edildi", cargo_company="MNG Kargo",
              tracking_number="MNG223344556", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-09", delay_risk=False, created_at="2026-05-06"),
        Order(order_id="107", customer_name="Ceren Yılmaz", product_name="Organik Badem",
              quantity=2, order_status="teslim_edildi", cargo_company="PTT Kargo",
              tracking_number="PTT334455667", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-10", delay_risk=False, created_at="2026-05-07"),
        Order(order_id="108", customer_name="Kerem Şahin", product_name="Bal",
              quantity=1, order_status="teslim_edildi", cargo_company="Aras Kargo",
              tracking_number="AR667788990", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-10", delay_risk=False, created_at="2026-05-07"),
        Order(order_id="109", customer_name="Dilan Polat", product_name="Kekik Yağı",
              quantity=3, order_status="teslim_edildi", cargo_company="Yurtiçi Kargo",
              tracking_number="YK778899001", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-11", delay_risk=False, created_at="2026-05-08"),
        Order(order_id="110", customer_name="Mert Aslan", product_name="Zeytinyağı",
              quantity=2, order_status="teslim_edildi", cargo_company="MNG Kargo",
              tracking_number="MNG445566778", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-11", delay_risk=False, created_at="2026-05-08"),
        # --- Kargoda (normal) ---
        Order(order_id="111", customer_name="Hale Özer", product_name="Organik Domates Kurusu",
              quantity=1, order_status="kargoda", cargo_company="Yurtiçi Kargo",
              tracking_number="YK889900112", tracking_status="Dağıtımda",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-11"),
        Order(order_id="112", customer_name="Tarık Güneş", product_name="El Yapımı Reçel",
              quantity=2, order_status="kargoda", cargo_company="PTT Kargo",
              tracking_number="PTT556677889", tracking_status="Dağıtım Merkezinde",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-11"),
        Order(order_id="113", customer_name="İpek Doğan", product_name="Kahve Çekirdeği",
              quantity=3, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR778899012", tracking_status="Şubede",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="114", customer_name="Serkan Ateş", product_name="Bal",
              quantity=1, order_status="kargoda", cargo_company="MNG Kargo",
              tracking_number="MNG667788991", tracking_status="Dağıtımda",
              estimated_delivery_date="2026-05-13", delay_risk=False, created_at="2026-05-10"),
        Order(order_id="115", customer_name="Nazlı Kurt", product_name="Tarhana",
              quantity=4, order_status="kargoda", cargo_company="Yurtiçi Kargo",
              tracking_number="YK990011223", tracking_status="Dağıtım Merkezinde",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-11"),
        # --- Kargoda (gecikme riskli) ---
        Order(order_id="128", customer_name="Ali Çelik", product_name="Kahve Çekirdeği",
              quantity=2, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR456789012", tracking_status="Transfer Merkezinde",
              estimated_delivery_date="2026-05-12", delay_risk=True, created_at="2026-05-08"),
        Order(order_id="129", customer_name="Nur Şahin", product_name="Zeytinyağı",
              quantity=2, order_status="kargoda", cargo_company="MNG Kargo",
              tracking_number="MNG111222333", tracking_status="Taşımada — Beklemede",
              estimated_delivery_date="2026-05-12", delay_risk=True, created_at="2026-05-09"),
        Order(order_id="130", customer_name="Gülsüm Erdoğan", product_name="Organik Badem",
              quantity=1, order_status="kargoda", cargo_company="PTT Kargo",
              tracking_number="PTT998877665", tracking_status="Şubede — Gecikmeli",
              estimated_delivery_date="2026-05-11", delay_risk=True, created_at="2026-05-08"),
        Order(order_id="131", customer_name="Okan Taş", product_name="Kekik Yağı",
              quantity=2, order_status="kargoda", cargo_company="Yurtiçi Kargo",
              tracking_number="YK112244668", tracking_status="Transfer Merkezinde",
              estimated_delivery_date="2026-05-12", delay_risk=True, created_at="2026-05-09"),
        Order(order_id="132", customer_name="Pınar Çakır", product_name="Bal",
              quantity=3, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR223355779", tracking_status="Taşımada — Gecikmeli",
              estimated_delivery_date="2026-05-11", delay_risk=True, created_at="2026-05-08"),
        # --- Hazırlanıyor ---
        Order(order_id="140", customer_name="Hasan Öztürk", product_name="Doğal Sabun",
              quantity=4, order_status="hazirlaniyor", cargo_company="Yurtiçi Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-15", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="141", customer_name="Sibel Yıldırım", product_name="Organik Domates Kurusu",
              quantity=1, order_status="hazirlaniyor", cargo_company="MNG Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-15", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="142", customer_name="Volkan Kaplan", product_name="Tarhana",
              quantity=5, order_status="hazirlaniyor", cargo_company="PTT Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-15", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="143", customer_name="Cansu Elmas", product_name="El Yapımı Reçel",
              quantity=2, order_status="hazirlaniyor", cargo_company="Aras Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-16", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="144", customer_name="Barış Demir", product_name="Zeytinyağı",
              quantity=3, order_status="hazirlaniyor", cargo_company="Yurtiçi Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-16", delay_risk=False, created_at="2026-05-13"),
        # --- Beklemede ---
        Order(order_id="135", customer_name="Zeynep Arslan", product_name="Tarhana",
              quantity=5, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-17", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="136", customer_name="Burak Koçak", product_name="Kahve Çekirdeği",
              quantity=2, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-17", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="137", customer_name="Aylin Güler", product_name="Doğal Sabun",
              quantity=6, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-17", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="138", customer_name="Cem Aktaş", product_name="Organik Badem",
              quantity=1, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-18", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="139", customer_name="Elif Sönmez", product_name="Bal",
              quantity=2, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-18", delay_risk=False, created_at="2026-05-13"),
        # --- İptal ---
        Order(order_id="120", customer_name="Tolga Ersoy", product_name="Kekik Yağı",
              quantity=1, order_status="iptal", cargo_company=None,
              tracking_number=None, tracking_status="İptal Edildi",
              estimated_delivery_date="2026-05-10", delay_risk=False, created_at="2026-05-07"),
        Order(order_id="121", customer_name="Leyla Mutlu", product_name="Tarhana",
              quantity=3, order_status="iptal", cargo_company=None,
              tracking_number=None, tracking_status="İptal Edildi",
              estimated_delivery_date="2026-05-11", delay_risk=False, created_at="2026-05-08"),
        # --- Ek siparişler (bugün / dün) ---
        Order(order_id="145", customer_name="Rüya Keskin", product_name="Organik Domates Kurusu",
              quantity=3, order_status="hazirlaniyor", cargo_company="MNG Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-16", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="146", customer_name="Selim Erdoğan", product_name="Bal",
              quantity=1, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-18", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="147", customer_name="Melis Akın", product_name="Zeytinyağı",
              quantity=2, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR334456780", tracking_status="Dağıtımda",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-11"),
        Order(order_id="148", customer_name="Onur Bulut", product_name="El Yapımı Reçel",
              quantity=4, order_status="kargoda", cargo_company="Yurtiçi Kargo",
              tracking_number="YK445567891", tracking_status="Dağıtım Merkezinde",
              estimated_delivery_date="2026-05-14", delay_risk=False, created_at="2026-05-11"),
        Order(order_id="149", customer_name="Yaren Özkan", product_name="Kahve Çekirdeği",
              quantity=2, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-19", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="150", customer_name="Furkan Yıldız", product_name="Doğal Sabun",
              quantity=3, order_status="hazirlaniyor", cargo_company="PTT Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-16", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="151", customer_name="Aslı Çınar", product_name="Organik Badem",
              quantity=2, order_status="kargoda", cargo_company="MNG Kargo",
              tracking_number="MNG556678902", tracking_status="Taşımada",
              estimated_delivery_date="2026-05-15", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="152", customer_name="Deniz Karaca", product_name="Kekik Yağı",
              quantity=1, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR667789013", tracking_status="Şubede",
              estimated_delivery_date="2026-05-15", delay_risk=False, created_at="2026-05-12"),
        Order(order_id="153", customer_name="Kaan Şimşek", product_name="Tarhana",
              quantity=3, order_status="teslim_edildi", cargo_company="Yurtiçi Kargo",
              tracking_number="YK778890124", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-12", delay_risk=False, created_at="2026-05-09"),
        Order(order_id="154", customer_name="Büşra Tan", product_name="Zeytinyağı",
              quantity=2, order_status="teslim_edildi", cargo_company="PTT Kargo",
              tracking_number="PTT889901235", tracking_status="Teslim Edildi",
              estimated_delivery_date="2026-05-12", delay_risk=False, created_at="2026-05-09"),
        Order(order_id="155", customer_name="Alp Turan", product_name="Bal",
              quantity=1, order_status="beklemede", cargo_company=None,
              tracking_number=None, tracking_status="Sipariş Alındı",
              estimated_delivery_date="2026-05-19", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="156", customer_name="Derya Bilgin", product_name="El Yapımı Reçel",
              quantity=5, order_status="hazirlaniyor", cargo_company="MNG Kargo",
              tracking_number=None, tracking_status="Sipariş Hazırlanıyor",
              estimated_delivery_date="2026-05-17", delay_risk=False, created_at="2026-05-13"),
        Order(order_id="157", customer_name="Umut Keskin", product_name="Kahve Çekirdeği",
              quantity=3, order_status="kargoda", cargo_company="Aras Kargo",
              tracking_number="AR778901246", tracking_status="Transfer Merkezinde",
              estimated_delivery_date="2026-05-13", delay_risk=True, created_at="2026-05-10"),
        Order(order_id="158", customer_name="Tuba Erdem", product_name="Organik Domates Kurusu",
              quantity=2, order_status="kargoda", cargo_company="PTT Kargo",
              tracking_number="PTT990012357", tracking_status="Taşımada — Beklemede",
              estimated_delivery_date="2026-05-12", delay_risk=True, created_at="2026-05-09"),
    ]

    products = [
        Product(product_name="Organik Domates Kurusu", stock_quantity=8,
                critical_stock_threshold=15, average_daily_sales=4.5,
                supplier_name="Ege Tarım A.Ş.", unit_price=85.0),
        Product(product_name="Zeytinyağı", stock_quantity=31,
                critical_stock_threshold=20, average_daily_sales=3.5,
                supplier_name="Ege Zeytinyağ Koop.", unit_price=250.0),
        Product(product_name="El Yapımı Reçel", stock_quantity=22,
                critical_stock_threshold=12, average_daily_sales=2.5,
                supplier_name="Anadolu Lezzetleri", unit_price=120.0),
        Product(product_name="Tarhana", stock_quantity=45,
                critical_stock_threshold=20, average_daily_sales=3.0,
                supplier_name="Geleneksel Gıda Ltd.", unit_price=65.0),
        Product(product_name="Doğal Sabun", stock_quantity=6,
                critical_stock_threshold=15, average_daily_sales=3.0,
                supplier_name="Doğal Yaşam Koop.", unit_price=45.0),
        Product(product_name="Kahve Çekirdeği", stock_quantity=19,
                critical_stock_threshold=20, average_daily_sales=5.0,
                supplier_name="Karadeniz Kahve A.Ş.", unit_price=180.0),
        Product(product_name="Organik Badem", stock_quantity=12,
                critical_stock_threshold=15, average_daily_sales=2.5,
                supplier_name="Ege Tarım A.Ş.", unit_price=220.0),
        Product(product_name="Bal", stock_quantity=28,
                critical_stock_threshold=15, average_daily_sales=3.0,
                supplier_name="Anadolu Arı Koop.", unit_price=195.0),
        Product(product_name="Kekik Yağı", stock_quantity=9,
                critical_stock_threshold=12, average_daily_sales=2.0,
                supplier_name="Doğal Yaşam Koop.", unit_price=95.0),
        Product(product_name="Portakal Marmeladı", stock_quantity=17,
                critical_stock_threshold=10, average_daily_sales=1.8,
                supplier_name="Anadolu Lezzetleri", unit_price=90.0),
        Product(product_name="Tahini", stock_quantity=35,
                critical_stock_threshold=15, average_daily_sales=2.2,
                supplier_name="Geleneksel Gıda Ltd.", unit_price=75.0),
        Product(product_name="Sumak", stock_quantity=4,
                critical_stock_threshold=10, average_daily_sales=1.5,
                supplier_name="Anadolu Baharat A.Ş.", unit_price=55.0),
        Product(product_name="Pul Biber", stock_quantity=50,
                critical_stock_threshold=20, average_daily_sales=4.0,
                supplier_name="Anadolu Baharat A.Ş.", unit_price=40.0),
        Product(product_name="Organik Ceviz", stock_quantity=14,
                critical_stock_threshold=15, average_daily_sales=2.8,
                supplier_name="Karadeniz Tarım Ltd.", unit_price=280.0),
        Product(product_name="Doğal Lavanta Yağı", stock_quantity=7,
                critical_stock_threshold=10, average_daily_sales=1.2,
                supplier_name="Doğal Yaşam Koop.", unit_price=130.0),
        Product(product_name="Siyah Sarımsak", stock_quantity=11,
                critical_stock_threshold=12, average_daily_sales=1.8,
                supplier_name="Geleneksel Gıda Ltd.", unit_price=160.0),
        Product(product_name="Keçiboynuzu Pekmezi", stock_quantity=23,
                critical_stock_threshold=12, average_daily_sales=1.6,
                supplier_name="Anadolu Lezzetleri", unit_price=110.0),
        Product(product_name="Organik Nohut", stock_quantity=60,
                critical_stock_threshold=25, average_daily_sales=5.5,
                supplier_name="Ege Tarım A.Ş.", unit_price=35.0),
        Product(product_name="Zeytin (Gemlik)", stock_quantity=38,
                critical_stock_threshold=20, average_daily_sales=4.2,
                supplier_name="Ege Zeytinyağ Koop.", unit_price=85.0),
        Product(product_name="Isırgan Otu Çayı", stock_quantity=5,
                critical_stock_threshold=10, average_daily_sales=1.4,
                supplier_name="Doğal Yaşam Koop.", unit_price=70.0),
    ]

    db.add_all(orders)
    db.add_all(products)
    db.commit()
    db.close()
